### ISSUE TITLE
core dumped

### ISSUE THREAD

**Issue by denizzzka** [skilion/onedrive#1]
```
$ make
dmd -O -release -inline -boundscheck=off -ofonedrive -L-lcurl -L-lsqlite3 -L-ldl patch/etc_c_curl.d patch/std_net_curl.d src/config.d src/itemdb.d src/main.d src/monitor.d src/onedrive.d src/sqlite.d src/sync.d src/util.d
$ ls
INSTALL.md  LICENSE  Makefile  onedrive  onedrive.conf  onedrive.o  patch  README.md  src
$ ./onedrive 
Ошибка сегментирования (core dumped)
```

**Comment by skilion** [comment]
It's probably because there isn't a config file in any of the predefined paths.
Just run `sudo make install` one time and everything should be fine.
This is a classical error case that never happens on the dev machine... I'll push a commit for this so it won't happen again.

---

Next time, before reporting a generic segfault (which doesn't say much)
1. try to compile it in debug mode (`make debug`), maybe you'll get a detailed error message.
2. if you still get a generic segfault, you'll have to run it in a debugger and get a backtrace when it crash.
