### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by cizra** [skilion/onedrive#117]
```
$ make
dmd -O -release -inline -boundscheck=off -ofonedrive -L-lcurl -L-lsqlite3 -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/sqlite.d src/sync.d src/upload.d src/util.d
src/onedrive.d(23): Error: @nogc function 'onedrive.OneDriveException.this' cannot call non-@nogc function 'object.Exception.this'
src/onedrive.d(269): Error: no property 'patch' for type 'int'
src/onedrive.d(266): Error: function onedrive.OneDriveApi.patch!char.patch no return exp; or assert(0); at end of function
src/onedrive.d(129): Error: template instance onedrive.OneDriveApi.patch!char error instantiating
src/sync.d(38): Error: @nogc function 'sync.SyncException.this' cannot call non-@nogc function 'object.Exception.this'
src/sync.d(43): Error: @nogc function 'sync.SyncException.this' cannot call non-@nogc function 'object.Exception.this'
make: *** [Makefile:19: onedrive] Error 1
```

```
$ dmd --version
DMD64 D Compiler v2.067.1-devel
Copyright (c) 1999-2014 by Digital Mars written by Walter Bright
```

**Comment by scottsisco** [comment]
I get a similar error.

**Comment by jaked122** [comment]
You need a newer dmd version.

**Comment by cscs75** [comment]
I have this "make" error, since last update.....

 # make
dmd -O -release -inline -boundscheck=off -ofonedrive -L-lcurl -L-lsqlite3 -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/sqlite.d src/sync.d src/upload.d src/util.d
src/onedrive.d(40): Error: function std.json.toJSON (const(JSONValue*) root, const(bool) pretty = false, const(JSONOptions) options = cast(JSONOptions)0) is not callable using argument types (const(JSONValue), bool)
Makefile:19: recipe for target 'onedrive' failed
make: *** [onedrive] Error 1

# dmd --version
DMD64 D Compiler v2.069.0
Copyright (c) 1999-2015 by Digital Mars written by Walter Bright

**Comment by skilion** [comment]
The compiler is out of date, last version is v2.072.1

**Comment by cscs75** [comment]
thank you, it works
