### ISSUE TITLE
OneDrive Business not supported

### ISSUE THREAD

**Issue by gur111** [skilion/onedrive#143]
Please please please add business support.

**Comment by Tekki** [comment]
Access to OneDrive for Business is technically the same with API 2.0 (@skilion: any plans to switch from 1.0 to 2.0?). **But** additionally the app needs a client ID from Azure AD, which costs money. For more informations look here: https://dev.onedrive.com/app-registration.htm#register-your-app-for-onedrive-for-business

**Comment by mhalano** [comment]
My college made a partnership with Microsoft so now students have access to a OneDrive account with 1TB, so this feature would be very helpful.

**Comment by snhirsch** [comment]
Seconded and thirded on the OneDrive for Business...  I really really need this feature.  What would have to happen for this to be implemented?

**Comment by skilion** [comment]
You can fork the repo and hack `src/onedrive.d` to make it work with OneDrive biz. Then we can plan how to merge

**Comment by Tekki** [comment]
First of all, the authorization code from OneDrive for Business looks completely different. This is an example: `https://login.microsoftonline.com/common/oauth2/nativeclient?code=OAQABAAIAAADRNYRQ3dhRSrm-4K-adpCJ4dv78miYLnKwT4_Y-wsUkJoAy6GGsJFrBQRxkSosAPLT9bRX95XWxZrCkdXCpLm8x6cNNc4RJHpsbF4Nvbnr4SphV-3y5Qd_2QG3hk8rlY0gWFRq0gEc91kQIgzxsdU-j94IrfkJmgLIy4dyqhgXvYoriEM8qauguu0nza7mVj8v3_rejMuSlEEMYEV8sZWKMJPPhX1GrLiajo3mHQyf9_x6K30jGRauEilQK5OZ6CprKmakbqCbm1hA7IGodersCglW97SeoAMZw6P5eGVUf1p41guJJASIg4YPJ5VX7XMym61CEmjr8sQH93ls4-I7SJ--ziZnToi1MhSyfeonSzMFJvBVddw7o7i1ekE8EUQJetCmKTxq_hTdA7vSaCEBIw59pLvnBagp19pSLO1Bsyd3DzcV8KpXPqL_HrhIYRM0droZuh7Gf731MQt-kD6X2SftULxH51dP0fyKKKBAnEoBXGPZopTM7Fe5eI2FIYdq4JjAyuB8xZl9L1QBAVSkNQIEdT3jaAsaUmSDJW2xFz9WGwSd1rRZztEd3Z_iWyGWLuyMkRhtvJ5R1ROoH4vCnkuFbWvxSfs1vkhB7cHSKiAA&session_state=e913d37a-1318-4804-a733-3d136edd16a0
`
In my Perl project (I'll upload it as soon as the code looks a bit better) I have no problems to connect to OneDrive for Business if I extract the code from the URL with an appropriate module instead of regex.
I'll take a closer look at it and give you more information.
Can you tell me how you registered your app permissions? At the moment I use your app-id for tests instead of my own.

**Comment by skilion** [comment]
For registering a new app refer to: https://dev.onedrive.com/app-registration.htm

**Comment by skilion** [comment]
As of 126f2719b838ef3ffb085591bb9fff62bd17e4f8 OneDrive for Business is supported
