### ISSUE TITLE
Issue installing as service Ubuntu 15.10 64b

### ISSUE THREAD

**Issue by kpirnie** [skilion/onedrive#25]
Getting this issue
Failed to get D-Bus connection: No such file or directory

After attempting to run:
systemctl --user enable onedrive
systemctl --user start onedrive

Nothing in log:
journalctl --user-unit onedrive -f

Only way I can get it to run is cmd line: onedrive --resync

How can I install it as a service?

**Comment by kevp75** [comment]
**Copying:** https://github.com/skilion/onedrive/blob/master/onedrive.service
**To:** /lib/systemd/system/onedrive.service

**And running:**
systemctl enable onedrive.service
systemctl start onedrive.service

May have done the trick, will post back in a minute after reboot

**Comment by kevp75** [comment]
No dice

root@GetYouOnline:~# systemctl status onedrive
● onedrive.service - OneDrive Free Client
   Loaded: loaded (/lib/systemd/system/onedrive.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2016-01-21 11:29:34 EST; 1min 28s ago
     Docs: https://github.com/skilion/onedrive
  Process: 745 ExecStart=/usr/local/bin/onedrive -m (code=exited, status=1/FAILURE)
 Main PID: 745 (code=exited, status=1/FAILURE)

Jan 21 11:29:34 GetYouOnline onedrive[745]: ??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5caa06]
Jan 21 11:29:34 GetYouOnline onedrive[745]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5ca95c]
Jan 21 11:29:34 GetYouOnline onedrive[745]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5ca9c2]
Jan 21 11:29:34 GetYouOnline onedrive[745]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5ca95c]
Jan 21 11:29:34 GetYouOnline onedrive[745]: ??:? _d_run_main [0x5ca8b9]
Jan 21 11:29:34 GetYouOnline onedrive[745]: ??:? main [0x5b1545]
Jan 21 11:29:34 GetYouOnline onedrive[745]: ??:? __libc_start_main [0x93b91a3f]
Jan 21 11:29:34 GetYouOnline systemd[1]: onedrive.service: Main process exited, code=exited, status=1/FAILURE
Jan 21 11:29:34 GetYouOnline systemd[1]: onedrive.service: Unit entered failed state.
Jan 21 11:29:34 GetYouOnline systemd[1]: onedrive.service: Failed with result 'exit-code'.

**Comment by kevp75** [comment]
Well...   we can sort of fake it by placing the following code into a /etc/init.d script, and running:

```ln -s /etc/init.d/onedrive /etc/rc3.d/S99onedrive```

to force it on boot

```
#!/bin/sh
# /etc/init.d/onedrive
### BEGIN INIT INFO
# Provides:          onedrive
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Put a short description of the service here
# Description:       Put a long description of the service here
### END INIT INFO

# Change the next 3 lines to suit where you install your script and what you want to     call it
DAEMON=onedrive
DAEMON_NAME=onedrive

# This next line determines what user the script runs as.
DAEMON_USER=root

do_start () {
    $DAEMON -m >/dev/null 2>&1 &
}
do_stop () {
    killall -9 onedrive;
}

case "$1" in

    start|stop)
        do_${1}
        ;;
    *)
       do_start
       ;;
esac
exit 0
```

**Comment by Scimmia22** [comment]
You need a session dbus running to use systemctl --user.
