### ISSUE TITLE
Repeatingly adding host name to files

### ISSUE THREAD

**Issue by globus68** [skilion/onedrive#265]
Hi!
After adding a file or editing a file in the OneDrive folder, the sync copies the new/edited file(s) and adds the computer host name to the file name. Eg. if I create a file in the OneDrive filder named test.docx, there will be two files in that folder afyer the first sync: test.docx and test-hilap.docx. After next sync again there will be three files: test.docx, test-hilap.docx and test-hilap-hilap.docx.

The last log lines:
Jan 02 09:48:05 hilap onedrive[1312]: Uploading: ./Newtest-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap.docx
Jan 02 09:48:07 hilap onedrive[1312]: Uploading: ./Test-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap.docx
Jan 02 09:49:32 hilap onedrive[1312]: Moving: Newtest-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap.docx -> ./Newtest-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap.docx
Jan 02 09:49:32 hilap onedrive[1312]: ./Newtest-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap.docx: No such file or directory
Jan 02 09:49:33 hilap onedrive[1312]: Downloading: ./Newtest-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap.docx
Jan 02 09:49:35 hilap onedrive[1312]: Moving: Test-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap.docx -> ./Test-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap.docx
Jan 02 09:49:35 hilap onedrive[1312]: ./Test-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap.docx: No such file or directory
Jan 02 09:49:36 hilap onedrive[1312]: Downloading: ./Test-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap.docx
Jan 02 09:49:37 hilap onedrive[1312]: Uploading: ./Test-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap.docx
Jan 02 09:49:38 hilap onedrive[1312]: Uploading: ./Newtest-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap.docx

**Comment by fiercebrake** [comment]
Greetings

That happened to me when my local folder had the wrong permissions and one
drive couldn't access/write the specific file; are your file permissions
and file owner properly set?

David Valiente

On Jan 2, 2018 02:51, "globus68" <notifications@github.com> wrote:

Hi!
After adding a file or editing a file in the OneDrive folder, the sync
copies the new/edited file(s) and adds the computer host name to the file
name. Eg. if I create a file in the OneDrive filder named test.docx, there
will be two files in that folder afyer the first sync: test.docx and
test-hilap.docx. After next sync again there will be three files:
test.docx, test-hilap.docx and test-hilap-hilap.docx.

The last log lines:
Jan 02 09:48:05 hilap onedrive[1312]: Uploading:
./Newtest-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap.docx
Jan 02 09:48:07 hilap onedrive[1312]: Uploading: ./Test-hilap-hilap-hilap-
hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap.docx
Jan 02 09:49:32 hilap onedrive[1312]: Moving: Newtest-hilap-hilap-hilap-
hilap-hilap-hilap-hilap-hilap-hilap-hilap.docx ->
./Newtest-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap.docx
Jan 02 09:49:32 hilap onedrive[1312]: ./Newtest-hilap-hilap-hilap-
hilap-hilap-hilap-hilap-hilap-hilap-hilap.docx: No such file or directory
Jan 02 09:49:33 hilap onedrive[1312]: Downloading:
./Newtest-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap.docx
Jan 02 09:49:35 hilap onedrive[1312]: Moving: Test-hilap-hilap-hilap-hilap-
hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap.docx ->
./Test-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-
hilap-hilap-hilap-hilap-hilap-hilap.docx
Jan 02 09:49:35 hilap onedrive[1312]: ./Test-hilap-hilap-hilap-
hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap.docx: No
such file or directory
Jan 02 09:49:36 hilap onedrive[1312]: Downloading: ./Test-hilap-hilap-hilap-
hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap.docx
Jan 02 09:49:37 hilap onedrive[1312]: Uploading: ./Test-hilap-hilap-hilap-
hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap.docx
Jan 02 09:49:38 hilap onedrive[1312]: Uploading:
./Newtest-hilap-hilap-hilap-hilap-hilap-hilap-hilap-hilap-
hilap-hilap-hilap.docx

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/skilion/onedrive/issues/265>, or mute the thread

**Comment by skilion** [comment]
Unfortunately, as of today, the monitor mode does not work very well if files are update continuously (let's say faster than 1 time per minute) and conflicts can arise which create copies of the files (this to avoid potential data loss). I would suggest you to edit the files outside the OneDrive directory and move them back only once you finished editing.

**Comment by globus68** [comment]
Thank you for replying fiercebrake!

I have checked the permissions. The local OneDrive folder is 755 and the 
created document inside the OneDrive folder is 644. As the sync service 
is owned by my user, the permissions should be OK, or am I missing anything?

Best regards

Vidar Evenrud Seeberg

**Comment by globus68** [comment]
Thank you for your reply, skillion!

I can see the problem. I will try the workaround and see if it works 
better then. Maybe I have to change my working habits a little... :)

Keep up the good work!

Best regards
Vidar Evenrud Seeberg

**Comment by thomasfedb** [comment]
@globus68 did the suggestions help you resolve the issue? If so, you might close the issue.

**Comment by globus68** [comment]
Hi, @thomasfedb!

I don't know if the issue should be closed. After all this is a real 
issue, which hopefully can be solved. My company is looking into storage 
solutions, OneDrive being one of them. Although a working procedure for 
Linux users of externally editing files and then sync back to the 
OneDrive folder could work, you could/would at some point forget to 
follow the procedure and possibly create some chaos.

I hope you find a solution to the issue. If this issue is a duplicate, 
just feel free to close it.

I appreciate your work, and keep up the good work!

Regards

Vidar

**Comment by thomasfedb** [comment]
Was just checking on the status of the issue @globus68.

**Comment by realProUser** [comment]
Hi,

I'm experiencing the same problem as globus68. 
The files that get the host name appended changes owner from www-data to root. Also file permissions change from 664 to 644.

So the workaround for me is to identify the affected files and delete them from both the server and from onedrive, and change owner/permissions  on the original file...

File extension doesn't matter, and just a fraction of the files is affected. Also, in our scenario all files on the server resides in the same folder.

**Comment by thomasfedb** [comment]
@realProUser OneDrive doesn't have any concept of permissions, and so neither does this project. I believe the expected use-case is syncing a directory inside your home folder, rather than running as root (which it seems you are doing).

**Comment by abraunegg** [comment]
This is the same issue as #171, #338, #343

There appears to be an issue in the local conflict handling routine in the original codebase. This will be the next item I look at.

**Comment by globus68** [comment]
Thank you for looking into this @abraunegg. I am looking forward to the fix. Keep up the good work you are doing!

**Comment by abraunegg** [comment]
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive

**Comment by globus68** [comment]
@abraunegg: I am still here😃. I will test tonight to see if the issue still persist. Currently I am working around the issue by keeping the documents in another folder and sync them into the onedrive folder now and then. I will report back tonight. Best regards Vidar

**Comment by globus68** [comment]
Hello again. I tried to reproduce the issue. However, I now get a "Key not found: lastModifiedDateTime" error, which is a different issue. I have to solve that first, but my time is very limited at the moment, so I have to come back to it

**Comment by abraunegg** [comment]
@globus68 
You are using the wrong code. This 'skilion' code branch is not maintained and has issues. You need to be using the latest code from my branch.

I suggest you close this issue, clone my repository, and see if you have any issues, then if you do - open an issue against my branch.

**Comment by globus68** [comment]
Aha, thanks @abraunegg, I will try tomorrow
