### ISSUE TITLE
session cannot handle status code 416 (Requested Range Not Satisfiable)

### ISSUE THREAD

**Issue by breunigs** [skilion/onedrive#3]
While uploading a file onedrive crashed (didn't get a coredump, but will try to next time). When restarting it, it tried to resume the upload with an apparently wrong fragment. Restarting it once more worked, though. The uploaded file is valid, i.e. its md5sum matches. Version is 9da9b7240df.

Here's the complete log:
```
./onedrive -v
(…)
Uploading fragment: 1226833920-1237319680/1660093275
Uploading fragment: 1237319680-1247805440/1660093275
Uploading fragment: 1247805440-1258291200/1660093275
[1]    31901 broken pipe  ./onedrive -v
```

```
./onedrive -v
Loading config ...
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/stefan/OneDrive
Initializing the Synchronization Engine ...
Trying to restore the upload session ...
Continuing the upload session ...
Uploading fragment: 1256191552-1266677312/1660093275
onedrive.OneDriveException@src/onedrive.d(282): HTTP request returned status code 416 (Requested Range Not Satisfiable)
----------------
./onedrive(std.json.JSONValue onedrive.OneDriveApi.uploadFragment(const(char)[], immutable(char)[], long, long, long)+0x56a) [0x5ac12a]
./onedrive(std.json.JSONValue upload.UploadSession.upload()+0x180) [0x5b9be0]
./onedrive(_Dmain+0x8cf) [0x5a5adf]
./onedrive(_D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv+0x1f) [0x5c0c27]
./onedrive(void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate())+0x2a) [0x5c0b82]
./onedrive(void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll()+0x2b) [0x5c0be3]
./onedrive(void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate())+0x2a) [0x5c0b82]
./onedrive(_d_run_main+0x1d2) [0x5c0b02]
./onedrive(main+0x12) [0x5a7a1a]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7f6c06d85b45]
[1]    2790 exit 1     ./onedrive -v
```

```
./onedrive -v
Loading config ...
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/stefan/OneDrive
Initializing the Synchronization Engine ...
Trying to restore the upload session ...
Continuing the upload session ...
Uploading fragment: 1258291200-1268776960/1660093275
Uploading fragment: 1268776960-1279262720/1660093275
(…)
```

**Comment by skilion** [comment]
I've already encountered the "broken pipe" error during slow downloads. It is a pain in the ass to debug because it is caused by libcurl, and it is difficult to replicate because it happens after several minutes on supposedly good connections.
Unfortunately, for now, I have no ideas on how to solve it.
***
About the "Requested Range Not Satisfiable" error: I'm fairly sure that the root cause is not in the client logic because the client explicitly asks the server what fragment it wants before resuming.
I speculate that since the client suddently interrupted the upload, the connection on the server side is still open and the server is keeping the incomplete fragment. After a while the connection times out, the server discards the incomplete fragment, and you can resume the upload.

Right now most OneDriveException are threated the same way, which is they crash the app, but in the future the client will be able to recover.

**Comment by breunigs** [comment]
I'll see if I uncover more about the "broken pipe" then and open a new bug if I manage. 

Also, crashing seems an acceptable behaviour for now, so feel free to close this ticket for cleanliness reasons.

**Comment by skilion** [comment]
Any help will be appreciated.
