### ISSUE TITLE
Upload only

### ISSUE THREAD

**Issue by fzeiser** [skilion/onedrive#306]
Is it possible to upload only? I want to use onedrive as a backup and be sure, that files on my local machine cannot be updated by the client accidentally.

So I guess something that corresponds to 
rsync -avh source/ dest/ --delete

**Comment by jumpy-jack** [comment]
Bump. Needing this too.

**Comment by jumpy-jack** [comment]
You can easily update the source files in src/ to add this functionality.

Comment out anything which downloads the files and deletes the files from onedrive.

**Comment by kred-jon** [comment]
which file?

**Comment by corupta** [comment]
hi, I wanted to do the same, to do soI used the
`sync_list` feature described in the readme

so I created a `~/.config/onedrive/sync_list` file and written `myCustomFolder`
then, I created the folder `~/OneDrive/myCustomFolder`

then moved whatever I want to upload to this folder and typed `onedrive` in terminal to upload

it's basically like this: I am telling this program to sync only this folder, and since that's a new folder (not existant in onedrive), sync process does not download from the onedrive.

**Comment by abraunegg** [comment]
@fzeiser @jumpy-jack @kred-jon @corupta 

Any update? This functionality is included in #314

**Comment by kred-jon** [comment]
Yeah! its work great! thank! :)

**Comment by abraunegg** [comment]
Can you close this case as it is now resolved?

**Comment by kred-jon** [comment]
Sure! but its not me opened it :(

**Comment by abraunegg** [comment]
@fzeiser 

Can you validate this open case against #314 as this issue is resolved.

**Comment by abraunegg** [comment]
@fzeiser @jumpy-jack @corupta

Any update?

**Comment by fzeiser** [comment]
resolved in  #314
