### ISSUE TITLE
Selective sync - main directory

### ISSUE THREAD

**Issue by kamilmaj** [skilion/onedrive#308]
I understand that I can only choose folders to sync in `sync_list`
But what if I want sync only files from main directory without folders?
Usually I'm saving files on my smartphone not in folders but in main directory of onedrive.

Below example of `sync_list` doesn't work
```
sync_list:
1  *.*
2
```

**Comment by jorge-leon** [comment]
Matching in `sync_list` is implemented with a prefix string match, no wildcard matching is possible.

You might be interested in the pull request #301 or wait, until it is merged.

With this modification you almost get what you want. List all directories with a '-' prefix in `sync_list` and
add a final line with an empty '+'.

You'd have to update the `sync_list` every time you add a directory to the drive.

Implementing exactly what you are looking for would be desirable, but propably requires a major rewrite.

**Comment by kamilmaj** [comment]
It looks ok, but I'm afraid I'm to green to successfully implement it
Please write quick procedure or send me link to right place from I can figure out how to do that.. through bash, file manager, copy paste code? :) 
And I understand that my path in `sync_list` file should look like `+New folder` eq...

**Comment by jorge-leon** [comment]
Follow the procedure exactly as described in the README.md file (https://github.com/skilion/onedrive),
**but** instead of
`git clone https://github.com/skilion/onedrive.git`
use
`git clone https://github.com/jorge-leon/onedrive.git` (my repository).

If the folders you do _not_ want to sync are called `Folder1`, `Folder2` and `Folder3,` then your `sync_list` file will look like:

```
-Folder1
-Folder2
-Folder3
+
```
The first three lines exclude the respective folder from syncing, the last line includes everything else.

**Note:** This is just a temporary solution to get a current onedrive with my patch. Do not rely on my repository to be up-to-date in the future. Keep checking skillion's repository, this feature or a similar one will surely be made available together with other improvements in the future there.

**Comment by kamilmaj** [comment]
Thank you for your help and code. This is enough good for me. Works.
I'm closing issue. Best regards.

**Comment by JuanRios** [comment]
Hi, I'm pretty new to this app. BTW congrats... Is working but I need some help.

a) Some folders with spaces in the name, inside 'sync_list' file are excluded, like "Docs For Living" or "Google Drive"
b) Some folder that should be excluded from 'config' file like: 
skip_dir = "Work/Company/Backup_Base/setup/|Work/Courses/Cursos Integrales Avanzados/Several Tests/"

are synced anyway :-1: 
Note: Folders to skip also have spaces between the folder names...

Any ideas?

Thanks in advance.

PS. I want to donate.

**Comment by abraunegg** [comment]
@JuanRios 
The 'skilion' code does not contain a feature that enables 'skip_dir' - so this is the reason why this does not work for you. This feature (skip_dir) is included in my fork - refer to: https://github.com/abraunegg/onedrive/blob/master/README.md#configuration

Also, the 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements like what you are looking for you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.
