### ISSUE TITLE
Error building under raspbian

### ISSUE THREAD

**Issue by carleslm** [skilion/onedrive#319]
First... I'm a real noob, so maybe this is a simple question. Please be patient :)

when I try to install using `sudo make DC=ldmd2 install`, after one minute or so, I get the next output:

> ...
> ...
> onedrive.o:(.data._D25TypeInfo_S3std5stdio4File6__initZ[_D25TypeInfo_S3std5stdio4File6__initZ]+0x1c): undefined reference to `_D3std5stdio4File11__xopEqualsFKxSQBgQBfQBcKxQmZb'
> collect2: error: ld returned 1 exit status
> Error: /usr/bin/gcc failed with status: 1
> Makefile:29: recipe for target 'onedrive' failed
> make: *** [onedrive] Error 1

ldc -version outputs:

> LDC - the LLVM D compiler (1.8.0):
>   based on DMD v2.078.3 and LLVM 5.0.1
>   built with LDC - the LLVM D compiler (1.7.0)
>   Default target: arm-unknown-linux-gnueabihf
>   Host CPU: cortex-a53
>   http://dlang.org - http://wiki.dlang.org/LDC
> 
>   Registered Targets:
>     arm     - ARM
>     armeb   - ARM (big endian)
>     thumb   - Thumb
>     thumbeb - Thumb (big endian)

any help would be appreciated. Thank you!! :D

**Comment by sibero80** [comment]
Have you tried doing the same procedure in two separate steps?
```
sudo make DC=ldmd2
sudo make install
```
I managed to successfully compile in Raspbian following the steps described in this issue #325 
you probably dont need to download the latest LDC compiler, because you seem to already be in 1.8.0, while I was in a much older version.
But if my suggestion does not work, then it would not hurt to download the LDC binaries and try it out, just in case anything is wrong with the distro one.

**Comment by carleslm** [comment]
Thank you so much ^^ 
Using the method you described in #325 worked at the first try :D

**Comment by abraunegg** [comment]
@carleslm 

If this issue is resolved, can you close this case out?

**Comment by carleslm** [comment]
Sure!
Case closed 😄
