### ISSUE TITLE
Error attempting to sync

### ISSUE THREAD

**Issue by jeanlucthumm** [skilion/onedrive#332]
Not sure what to make of this:
```
~ » onedrive -v
Loading config ...
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/jeanluc/OneDrive
Initializing the Synchronization Engine ...
Applying changes of C61999D1268EFAFA!123
Delta link expired, resyncing...
JSONValue is not an object
Applying changes of C61999D1268EFAFA!123
Delta link expired, resyncing...
JSONValue is not an object
Applying changes of C61999D1268EFAFA!123
Delta link expired, resyncing...
std.json.JSONException@std/json.d(260): JSONValue is not an object
----------------
??:? pure @safe void std.exception.bailOut!(std.json.JSONException).bailOut(immutable(char)[], ulong, const(char[])) [0xfeec7397]
??:? pure @safe bool std.exception.enforce!(std.json.JSONException, bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0xfeec7311]
??:? inout pure @property @trusted inout(std.json.JSONValue[immutable(char)[]]) std.json.JSONValue.objectNoRef() [0xfee802e1]
??:? const pure @safe const(std.json.JSONValue)* std.json.JSONValue.opBinaryRight!("in").opBinaryRight(immutable(char)[]) [0xfee50c7b]
??:? void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[]) [0xfee56c95]
??:? void sync.SyncEngine.applyDifferences() [0xfee56851]
??:? void main.performSync(sync.SyncEngine) [0xfee46cf3]
??:? _Dmain [0xfee46850]

```

Happens every time .

**Comment by abraunegg** [comment]
Unsure why this is exactly happening, however in the original code base the error message your getting is when the client gets a 410 code:

410     Gone     The requested resource is no longer available at the server.

In #314 I added a lot of additional checking and to gracefully handle some errors, but I didn't add 410

Because 'changes' is not being returned as a valid JSONValue to parse - this is why the code is failing. 

onedrive.d get() method where it returns the response needs to ensure that the response is always a valid JSONValue.

**Comment by abraunegg** [comment]
@jeanlucthumm 

Any update?

**Comment by abraunegg** [comment]
@jeanlucthumm 
Any update?

**Comment by jeanlucthumm** [comment]
No update. Problem remains

**Comment by abraunegg** [comment]
Did you upgrade your code to the #314 branch?

**Comment by abraunegg** [comment]
@jeanlucthumm 
Any update when using #314?

**Comment by abraunegg** [comment]
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive
