### ISSUE TITLE
Need example to select or skip folders

### ISSUE THREAD

**Issue by cakebytheoceanLuo** [skilion/onedrive#352]
Assumed I have 3 folder in my onedrive, A, B and C.
I just want to select and sync folder C so to skip A and B.

How can i achieve it. I know it is told in the readme doc.
I have tried with adding  `sync_dir C` to `~/.config/onedrive/config`
But it still would download all the files.

**Comment by abraunegg** [comment]
@cakebytheoceanLuo 
So the robustness of sync_dir is unknown at this point in time.

In #314 this introduces the switch `--single-directory` where you can sync a specific folder within your ~/OneDrive/ root.

**Comment by cakebytheoceanLuo** [comment]
Sorry. I stil can't find it.
Is this what you mean?
https://github.com/skilion/onedrive/pull/314/commits/ccd4dfbaf722d732ef273c5e39cd4aed90ea2dae

But i can't figure out how to sync the folder that i select.

**Comment by abraunegg** [comment]
There are 2 ways to get the latest code:

Option 1:
```
git clone https://github.com/skilion/onedrive.git
git fetch origin pull/314/head:pr314
git checkout pr314
make
make install
```

Option 2:

```
git clone https://github.com/abraunegg/onedrive.git
make
make install
```

**Comment by abraunegg** [comment]
@cakebytheoceanLuo 
> But should i always give the command onedrive --synchronize --single-directory '<dir_name>', when i only want the selected folders.

yes correct,

Imagine the following local folders:

```
~/OneDrive/A
~/OneDrive/B
~/OneDrive/C
```

In your original example you only want to sync folder C:

```
onedrive --synchronize --single-directory 'C'
```

or with verbose logging:

```
onedrive --synchronize --verbose --single-directory 'C'
```

> In the file ~/.config/onedrive/config should i just give sync_dir <dir_name>. And i dont have to always give the long command. Is that right? But it don't work for me.

The sync_dir property is to change ~/OneDrive to "something else" however there is a massive caveat here. In the database that the client uses, all 'files & folders' are recorded as being 'relative' to this sync_dir path.

If you then go and change it & sync 'something else' that sync operation will 'think' that you have deleted the files & delete them from OneDrive.

It is better to keel sync_dir the 'default', and then use symbolic links in that directory to content elsewhere to sync.

It really is something that needs to be fixed (how items are recorded) so that when changing the sync_dir undesirable things dont happen.

**Comment by abraunegg** [comment]
@cakebytheoceanLuo 
Any update?

**Comment by cakebytheoceanLuo** [comment]
Sorry i just had a exam about operations research.
I have try with the automatic upload service, but i work but the default setting, which uploads and downloads all the files.
So i just can try with the command `onedrive --synchronize --verbose --single-directory 'C'`, in aim to download selected folders.
Thx.
