### ISSUE TITLE
CPU running at 100 percent non-stop

### ISSUE THREAD

**Issue by GhostInTheMachines** [skilion/onedrive#373]
For some reason one drive is pegging one core of my laptop for the last couple of days.  I have had the service running for a couple of weeks so it seems strange that it would just start doing this.

My OS is Ubuntu LTS 16.04
Processor is a 7th generation I7 HQ 3770
16 gigs of memory

Let me know if there is some way to give you some debug information to see what is going on.

![image](https://user-images.githubusercontent.com/19687896/41314880-9037f640-6e53-11e8-9325-c7d8ec509059.png)

**Comment by abraunegg** [comment]
Hi,

The 'skilion' code appears to have been abandoned and contains issues that have not been fixed. Any issues, suggestions & feature requests will not be looked at under this github repository.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by K1ngjulien** [comment]
might be fixed by now c2cdb24131ad3b1c9f62562561510a931db2b72a

**Comment by abraunegg** [comment]
@K1ngjulien 
Actually it wont be and is actually fixed via this: https://github.com/abraunegg/onedrive/pull/419 - the actual cause is a number of contributing factors.

The good news is that this is fixed in my fork.

Also, the 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive
