### ISSUE TITLE
error during synchronization

### ISSUE THREAD

**Issue by turekm** [skilion/onedrive#387]
hello

1) thanks for very nice app
2) time to time it does not work and crashed due to https://pastebin.com/c8HE9pBf
could you have look? in case of another question be free to contact me

thank in advance
regards

**Comment by turekm** [comment]
13:46:39 mturek@5C-51-4F-7E-AF-31:~# onedrive --version
onedrive v1.1.1-2-gc231b13

**Comment by abraunegg** [comment]
Hi,

Your error when looking at the error log is `Key not found: lastModifiedDateTime`. This is fixed by PR #314, but also detailed in #380, #372, #351, #337

Additionally, the 'skilion' code appears to have been abandoned by the original author and contains issues that have not been fixed. Any issues, suggestions & feature requests will not be looked at under this github repository.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by turekm** [comment]
ok 

(continue on https://github.com/abraunegg/onedrive)
