### ISSUE TITLE
Internal database error: Disk I/O, no sync

### ISSUE THREAD

**Issue by Tasty213** [skilion/onedrive#421]
try to sync using
sudo onedrive --synchronize --verbose --resync
and it errors out to 
https://pastebin.com/EZ0c9e77

**Comment by abraunegg** [comment]
@Tasty213 
It appears your using my branch rather than the skilion branch - please close this case and open here: 

https://github.com/abraunegg/onedrive

Secondly, your running the client via sudo. What this does is run the client as the 'root' user, thus will mess up all the permissions for your normal user.

Regarding your issue:
```
A database statement execution error occurred: disk I/O error
```

This means you have either a disk problem - permissions, disk space issue or something else going on. The 'onedrive' application cant perform any disk operations.

**Comment by lewis2e** [comment]
> This means you have either a disk problem - permissions, disk space issue or something else going on. The 'onedrive' application cant perform any disk operations

Or the onedrive application is simply already running, as just happened to me.

Leaving this comment here for anyone else finding this post by Googling the error message (like I did). Check if onedrive is already running (e.g. if you have created a script to run it on log-in).

Kill the existing instance with `pkill -f onedrive`
.

**Comment by abraunegg** [comment]
@lewis2e
That will also assist - but if your running the skilion version - you are putting yourself at a significant data loss risk as well ...

**Comment by Troublor** [comment]
I encountered this problem too but I addressed it by stopping the onedrive.service running background using `systemctl --user stop onedrive.service`

**Comment by abraunegg** [comment]
@Troublor
The 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. It contains defects that put you at risk of data loss and corruption. If you wish to use the latest code which contains numerous fixes and enhancements you need clone & build from here: https://github.com/abraunegg/onedrive

**Comment by Troublor** [comment]
@abraunegg Yes, I'm using your branch of onedrive client

**Comment by abraunegg** [comment]
@Troublor
OK .. good to know .. but if you have an issue dont post or respond here - as this is the wrong location
