### ISSUE TITLE
is there a way to see used/left space?

### ISSUE THREAD

**Issue by kurokirasama** [skilion/onedrive#423]

**Comment by abraunegg** [comment]
> is there a way to see used/left space? 

Your feature request has been already added to my branch. At application run time it tells you the about of OneDrive free space left, plus after each successful upload what the new count is. Additional checks are also made so that files can only be uploaded if there is enough free space.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by kurokirasama** [comment]
cool! thankz!
