### ISSUE TITLE
Version inconsistency with Synaptic v onedrive --version

### ISSUE THREAD

**Issue by EvoEvz** [skilion/onedrive#426]
Hi is this a bug or is my install incorrect? I have tried reinstalling. Thanks

https://1drv.ms/u/s!Ajj783zGADEkgdEfcEaCL4chFkG_ZA

**Comment by abraunegg** [comment]
It is correct because your installing via Ubuntu package which is out of date:

https://bugs.launchpad.net/ubuntu/+source/onedrive/+bug/1790432

Best way to fix is to uninstall the package and compile from source. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by EvoEvz** [comment]
Yes installed via repositories. Is there any chance you will be adding yours to the repo's soon?

**Comment by abraunegg** [comment]
> Yes installed via repositories. Is there any chance you will be adding yours to the repo's soon?

I wont be adding my forked version to any Ubuntu repo anytime soon. It would be best for you to review the above launchpad bug and put your feedback there if you want the Ubuntu package updated. The more people that do that, the better chance that it gets updated.

Additionally, I don't use Ubuntu myself, nor do I have any desire to create & maintain a Ubuntu package - sorry.

**Comment by abraunegg** [comment]
> Do you have a guide for newbies on how to "compile from source"? 

All instructions are here - https://github.com/abraunegg/onedrive/blob/master/README.md

Follow them and you should not have an issue in compiling the software. 

> What about adding yours as Flatpak or Snap?

Again - no desire to do so.

**Comment by EvoEvz** [comment]
Hi abraunegg. Haha yeah I saw those instructions. I asked for a guide for newbies! I don't even know if I need to install the dependencies myself or whether I use DMD or LDC (whatever they are?)

Is that just too bad for now until I learn a lot more about Linux which I am prepared to do btw or is there an easier way, not really...

**Comment by EvoEvz** [comment]
Installed via PPA now for Ubuntu. Thanks very much for creating this app.
