### ISSUE TITLE
Using Cron with Onedrive Sync - Database Lock error in logs

### ISSUE THREAD

**Issue by ADun3306x** [skilion/onedrive#452]
Set up crontab entry to provide an email every 1 hour re Onedrive Sync Activity, however getting the following error from sqlite3 re locked database in logs

sqlite.SqliteException@src/sqlite.d(147): database is locked

The service is in my Ubuntu Startup programs  & cron scheduled to run it every hour and then email me the results log

I am able to sync using the scipts, however unsure why the error or whats causing it ?
Is it due to having onedrive in Startup and also running via cron?  Ie a conflict?
Cant seem to find a way of unlocking the db in question or what to do

Any help appreciative
Thnx

**Comment by abraunegg** [comment]
@ADun3306x 
When using cron, the 'skilion' client does not handle the correct shell environment determination, thus, what happens is you get database access issues / locking as you are seeing - ie - known issue and bug.

The good news is - the database locking / shell environment is all fixed in my fork - https://github.com/abraunegg/onedrive

> Is it due to having onedrive in Startup and also running via cron? Ie a conflict?

Yes it will be a conflict that is unhandled in the skilion codebase thus crashes the application and leaves the database in an unclean state.

> Cant seem to find a way of unlocking the db in question or what to do

When using my fork, your cron script might be better off using the `--display-sync-status` flag as well


If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by ADun3306x** [comment]
Amazing... Thanks @abraunegg for your quick response and solutions. Have also migrated over to your branch and works like a charm!

**Comment by TrinhDinhPhuc** [comment]
onedrive --resync

**Comment by abraunegg** [comment]
@TrinhDinhPhuc 
> onedrive --resync

This is the wrong solution for the issue initially raised by @ADun3306x . This issue is correctly resolved by using my fork of this abandoned client.

@ADun3306x - this issue is still open, worth closing as this GitHub repo is defunct / abandoned.
