### ISSUE TITLE
Unable to authenticate on first run - no URI returned, empty file 'nativeclient' downloaded

### ISSUE THREAD

**Issue by jrp13149** [skilion/onedrive#455]
There seems to be different behavior from expected on the microsoft website. I can use the onedrive URL to login, and approve access, but it doens't give me a URI, it just offers a file to download, called 'nativeclient'. The file is empty.

How can I change this behaviour to get the URI I need?

Thanks.

**Comment by abraunegg** [comment]
@jrp13149 
I have seen this behaviour with Chrome myself, whereas Firefox there is no issue.

I suspect this is an issue with OneDrive / OneDrive API / OneDrive website rather than the client

Also, the 'skilion' code appears to have been abandoned and contains issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by abraunegg** [comment]
Submitted issue here: https://github.com/OneDrive/onedrive-api-docs/issues/1019

**Comment by jrp13149** [comment]
Switched to the actively supported fork at: [https://github.com/abraunegg/onedrive], no further problems.
