### ISSUE TITLE
onedrive command doesn't seem to reupload updated files properly

### ISSUE THREAD

**Issue by NetherKing1357** [skilion/onedrive#456]
I use onedrive to sync calibre. Added books are uploaded to the drive, but the library file isn't. To confirm this, I made small changes to some of the files and sure enough they weren't reuploaded or updated. Is there any way to make this work?

**Comment by abraunegg** [comment]
@NetherKing1357 
This is one of the many 'bugs' with this client that I have fixed in my fork.

Also, the 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by NetherKing1357** [comment]
> @NetherKing1357
> This is one of the many 'bugs' with this client that I have fixed in my fork.
> 
> Also, the 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive
> 
> If you have any issues when using my branch submit your issue against my branch for resolution & management.

Thanks a lot for the quick reply, will do!
