### ISSUE TITLE
Questions: About stability

### ISSUE THREAD

**Issue by GammaPi** [skilion/onedrive#458]
What will happen when a disk failure happens and the sync folder becomes unreadable or umounted? Will the remote file also be affected?

What does --resync actually do? What does it really mean by "Forget the last saved state, perform a full sync"? Will it sync files that are already in the cloud?

 Can I sync by manually instead of automatically?

**Comment by GammaPi** [comment]
What if the sync process take too long and the onedrive --resync is executed twice?

**Comment by GammaPi** [comment]
Can I get a email notification when the sync is done?

**Comment by abraunegg** [comment]
@GammaPi 
> What will happen when a disk failure happens and the sync folder becomes unreadable or umounted? Will the remote file also be affected?

If using the 'skilion' client, yes remote files will be affected - most likely deleted.

> What does --resync actually do? What does it really mean by "Forget the last saved state, perform a full sync"? Will it sync files that are already in the cloud?

If using the 'skilion' client, yes it will attempt to download & re-upload all files to get in a consistent state rather than determining what actually needs to be done to get 'back in sync'

> Can I sync by manually instead of automatically?

Yes you can

> What if the sync process take too long and the onedrive --resync is executed twice?

No real issue 

> Can I get a email notification when the sync has failed?

Not with the 'skilion' client

Also, the 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. If you wish to use the latest code which contains numerous bug fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by GammaPi** [comment]
@abraunegg 
Thank you very much both for your kind response and your forked repo.
Features such as upload only、download only 、no-remote-delete is really helpful when it comes to backup.
I also want to thank the original repo author.
