### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by esaintpierre** [skilion/onedrive#461]
I get the following after `make`:
enrique@Naranja ~/onedrive $ make
echo v1.1.3 >version
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
src/onedrive.d(37): Error: function std.json.toJSON (const(JSONValue*) root, const(bool) pretty = false, const(JSONOptions) options = cast(JSONOptions)0) is not callable using argument types (const(JSONValue), bool)
make: *** [onedrive] Error 1

**Comment by abraunegg** [comment]
@esaintpierre 
what compilation error are you facing?

**Comment by abraunegg** [comment]
@esaintpierre 
This is one of the many 'bugs' with this client that I have fixed in my fork.

Also, the 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.
