### ISSUE TITLE
'No config file found' on Raspbian

### ISSUE THREAD

**Issue by robinc64** [skilion/onedrive#462]
Hi!

When trying to use the version included in the Raspbian repos (1.1.20161012-2) it will fail with the following:
`object.Exception@src/config.d(30): No config file found`

The man page instructs to make a copy from /usr/local/etc/onedrive.conf but there was no file installed there. I did find one a onedrive.conf in /etc/ and made a copy of that one to ~/.config/onedrive/config. For completeness, the contents are:
`client_id = "000000004C15842F"`
`sync_dir = "~/OneDrive"`
`skip_file = ".*|~*"`
`skip_dir = ".*"`

I also tried using --confdir:
`onedrive --confdir ~/.config/onedrive`
`object.Exception@src/config.d(30): No config file found`

Help? :)

**Comment by abraunegg** [comment]
@robinc64 
Most likely you are hitting a known bug where `~` is not handled correctly. This is one of the many 'bugs' with this client that I have fixed in my fork.

Also, the 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by robinc64** [comment]
@abraunegg 
Thanks for your response. I will try building your version.
