### ISSUE TITLE
Syncing stops without error

### ISSUE THREAD

**Issue by lvictorino** [skilion/onedrive#466]
Trying to sync my OneDrive directories... and everything works fine until the script stops while syncing is not over. If I run onedrive script again, syncing resumes to the last file it was syncing before stopping by itself. Verbose mode doesn't give hints about what happens but here it is.
```
Downloading Documents/Bonjour M.docx... done.
Processing 2F162764F61DF28B!246089 TalkSESSAD-video-game.pptx
File
Downloading Documents/TalkSESSAD-video-game.pptx... done.
Processing 2F162764F61DF28B!246926 DevoxxUK-script.docx
File
Downloading Documents/DevoxxUK-script.docx...[lvictorino@machine onedrive]$ 
```

**Comment by abraunegg** [comment]
@lvictorino 
This sounds like OneDrive error response handling that is not handled very well by the 'skilion' version of the onedrive client. This is fixed in my fork.

Also, the 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

**Comment by lvictorino** [comment]
@abraunegg will do, thanks.

**Comment by gitforwebwork** [comment]
@abraunegg I am really happy that you are so actively working on this! "skillion" seems to have fallen off the face of the earth end of last year... :(
