### ISSUE TITLE
Feature Request : Running One-drive as daemon on startup

### ISSUE THREAD

**Issue by surapuramakhil** [skilion/onedrive#480]
it's very annoying for someone to press command to maintain folders in sync with one drive.
`onedirve -m`

**Comment by abraunegg** [comment]
@surapuramakhil 
The client already does this - refer to https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md in regards to enabling applicable user services via systemd or init.d

As advised before - 'skilion' has abandoned this git repo. Bugs exist and it is not maintained. You are running a buggy / old version that contains many defects and put you at risk of local & remote data loss.

**Comment by surapuramakhil** [comment]
@abraunegg  which onedrive will be install when I do this
`apt install onedrive`
in ubuntu

**Comment by abraunegg** [comment]
@surapuramakhil 
No idea ..

Check with `onedrive --version`

Most likely - old version. Compile from source to ensure you get the right version.

**Comment by surapuramakhil** [comment]
onedrive v1.0.1

**Comment by abraunegg** [comment]
@surapuramakhil 
This is a **very very very** old version and contains **so so so** many bugs and issues. There is no wonder you are having problems.

Suggest you do the following:

1. Remove the package (its broken, don't use it) - `apt-get remove onedrive; apt-get purge onedrive`
2. Install from source using these instructions: https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md - follow everything for your version of Ubuntu

**Comment by surapuramakhil** [comment]
@abraunegg can make your one drive installable by Linux apt install mechanism

**Comment by abraunegg** [comment]
@surapuramakhil 
It already is:
* https://packages.ubuntu.com/search?keywords=onedrive&searchon=names&suite=all&section=all
* https://packages.debian.org/search?keywords=onedrive

However the Ubuntu package is also way out of date. You are better using the Debian package if you want to use packages - but compiling from source is very easy and this is what you should be doing if you want an up to date client that works.

**Comment by MrClever** [comment]
Because the install process has a `make install` step you can usually substitute that for `checkinstall` in Debian and it's derivatives that use the `deb` packaging system. Here's what you need to do:
1. Follow the steps in the [compilation instructions](https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#compilation--installation) but **DONT** run the `sudo make install` step
2. Install the `checkinstall` package: `sudo apt install checkinstall`
3. Now replace `make install` with `checkinstall` - usually no need for sudo as `checkinstall` will create a deb package in the same directory as the source code.

Depending on the information you fed into `checkinstall` you will now have a `OneDrive_XXXXX_arch.deb` \*  file you can install with `dpkg`, ie `sudo dpkg -I OneDrive_XXXXX_arch.deb`.

\* where `XXXXX` is the version and `arch` is `amd64`, `arm64` etc.

Once the package is installed you can use normal package management commands/systems to remove it, see where the files are installed etc.

**Comment by abraunegg** [comment]
@MrClever 
The 'skilion' code appears to have been abandoned and contains many other issues that have not been fixed. It contains defects that put you at risk of data loss and corruption. If you wish to use the latest code which contains numerous fixes and enhancements you need clone & build from here: https://github.com/abraunegg/onedrive

**Comment by MrClever** [comment]
@abraunegg - cheers. I thought I was actually in the new Git project, so ignore my previous :) Really with this old project was more obviously flagged as "deprecated".

**Comment by abraunegg** [comment]
> Really with this old project was more obviously flagged as "deprecated".

So do I ... unfortunately no way to do anything in that regard except keep posting here when folk submit an issue or comment ..
