### ISSUE TITLE
Bound function does not support the escape function annotation

### ISSUE THREAD

**Issue by Pro** [skilion/onedrive#498]
Running the onedrive client on my files synchronizes most of the files, but then the onedrive client crashes with:

```
onedrive.OneDriveException@src/onedrive.d(408): HTTP request returned status code 400 (Bad Request)
{
    "error": {
        "code": "BadRequest",
        "innerError": {
            "date": "2020-02-06T10:22:00",
            "request-id": "<REMOVED>"
        },
        "message": "The request URI is not valid. The bound function binding to 'microsoft.graph.driveItem' does not support the escape function annotation."
    }
}
----------------

```

The Problem in that file is that it contains a colon `:`

I.e. `Example: Hello.pdf`

Is there a better way to handle this exception, i.e., replacing invalid characters before uploading the file?

**Comment by abraunegg** [comment]
@Pro 
The 'skilion' repo appears to have been abandoned and contains many defects that put you at risk of data loss and corruption if you use it. The original author is totally uncontactable despite numerous efforts by myself and others.

If you wish to use the latest code which contains numerous fixes and enhancements you need to clone & build from this repo: https://github.com/abraunegg/onedrive 

To be notified of new releases / bug fixes please also watch the above repo.

#### Major differences / Enhancements:
- Existing bugs with 'skilion' client fixed
- File upload / download validation to ensure data integrity
- SharePoint / Office 365 Shared Libraries added
- Desktop notifications via libnotify
- Dry-run capability to test configuration changes
- Prevent major OneDrive accidental data deletion after configuration change


In regards to your specific issue - this 'bug' is most certainly fixed in the above named repo.

**Comment by Pro** [comment]
Thanks for the update!
I'll switch to your implementation and test it.
