### ISSUE TITLE
Duplicate files with format filename-username.ext

### ISSUE THREAD

**Issue by decadenza** [skilion/onedrive#503]
I'm working on Debian 10. My config does sync every 2 minutes.
While working on a file "filename.ext" I continuously find a new file called _filename-MYUSERNAME.ext_ in the same folder.
If I don't delete, it continues creating _filename-MYUSERNAME2.ext_ and so on.

What's the reason of this?

**Comment by abraunegg** [comment]
@decadenza 
This is a known bug that is fixed in my fork.

The 'skilion' repo appears to have been abandoned in 2018 and contains many defects that put you at risk of data loss and corruption if you use it. The original author is totally uncontactable despite numerous efforts by myself and others.

If you wish to use the latest code which contains numerous fixes and enhancements you need to clone & build from this repo: https://github.com/abraunegg/onedrive 

To be notified of new releases / bug fixes please also watch the above repo.

#### Major differences / Enhancements:
- Existing bugs with 'skilion' client fixed
- File upload / download validation to ensure data integrity
- SharePoint / Office 365 Shared Libraries added
- Desktop notifications via libnotify
- Dry-run capability to test configuration changes
- Prevent major OneDrive accidental data deletion after configuration change

**Comment by decadenza** [comment]
Actually I was using debian experimental package [here](https://packages.debian.org/sid/net/onedrive).

I appreciate your work. I will follow that repository. It will be good to see your repository on the Debian package one day.

Thanks.

**Comment by abraunegg** [comment]
@decadenza 
In that case:

1. Open an issue in the correct location: https://github.com/abraunegg/onedrive
2. Follow the correct process to report an issue: https://github.com/abraunegg/onedrive#reporting-issues - most critical is a verbose debug log to identify what is going on and why, plus provides the details to fix.

Please do not open new issues here on the 'skilion' repo as this is not maintained and has not been for over 2 years.
