### ISSUE TITLE
error when make

### ISSUE THREAD

**Issue by jdavid54** [skilion/onedrive#514]
make  

    echo v1.1.3 >version
    dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
    src/qxor.d(2): Deprecation: module std.digest.digest is deprecated - import std.digest instead of std.digest.digest. std.digest.digest will be removed in 2.101
    src/qxor.d(88): Error: template instance WrapperDigest!QuickXor template WrapperDigest is not defined
    make: *** [Makefile:29 : onedrive] Erreur 1

**Comment by abraunegg** [comment]
@jdavid54 

The 'skilion' repo was abandoned in 2018 and contains many defects that put you at risk of data loss and corruption if you use it. The original author is totally uncontactable despite numerous efforts by myself and others. Do not use this repo. 

The latest and maintained code can be found here: https://github.com/abraunegg/onedrive 

To be notified of new releases / bug fixes please 'star' and 'watch' the new repo location.

#### Major differences / Enhancements:
- Existing bugs with 'skilion' client fixed
- File upload / download validation to ensure data integrity
- Support for SharePoint / Office 365 Shared Libraries 
- Support for OneDrive Business Shared Folders
- Desktop notifications via libnotify
- Dry-run capability to test configuration changes
- Prevent major OneDrive accidental data deletion after configuration change
- Support National Azure Cloud instances

Regarding your compiler issue - it is fixed in repository above.
