### ISSUE TITLE
HTTP request returned status code 400 (Bad Request)

### ISSUE THREAD

**Issue by rabayuugi** [skilion/onedrive#517]
I'm running this on Ubuntu 20.04 using version 1.1.3. I've followed the instructions on how to install. When I run onedrive --verbose and enter the URI, this is what outputs:

>onedrive.OneDriveException@src/onedrive.d(408): HTTP request returned status code 400 (Bad >Request)
>{
>    "correlation_id": "18513b11-b82d-42a1-ac67-6792518e5ef6",
>    "error": "invalid_grant",
>    "error_codes": [
>        70000
>    ],
>    "error_description": "AADSTS70000: The provided value for the 'code' parameter is not >valid.\r\nTrace ID: 4b7576da-6e2d-4d6d-b981-d573df349f00\r\nCorrelation ID
>    "error_uri": "https:\/\/login.microsoftonline.com\/error?code=70000",
>    "timestamp": "2020-09-30 02:44:12Z",
>    "trace_id": "4b7576da-6e2d-4d6d-b981-d573df349f00"
>}
>----------------
>src/onedrive.d:33 void onedrive.OneDriveApi.checkHttpCode(ref const(std.json.JSONValue)) >[0x55682d62820c]
>src/onedrive.d:333 std.json.JSONValue onedrive.OneDriveApi.post!(char).post(const(char)[], >const(char)[]) [0x55682d6283ae]
>src/onedrive.d:252 void onedrive.OneDriveApi.acquireToken(const(char)[]) [0x55682d6274e1]
>src/onedrive.d:237 void onedrive.OneDriveApi.redeemToken(const(char)[]) [0x55682d6273c6]
>src/onedrive.d:84 bool onedrive.OneDriveApi.authorize() [0x55682d626422]
>src/onedrive.d:64 bool onedrive.OneDriveApi.init() [0x55682d626253]
>src/main.d:100 _Dmain [0x55682d61ecc6]

Thanks for your assistance!

**Comment by abraunegg** [comment]
@rabayuugi 

The 'skilion' repo is defunct and was abandoned in 2018. Do not use this repo or follow instructions to use this repo.

Your actual issue is the same as:
* https://github.com/skilion/onedrive/issues/512
* https://github.com/skilion/onedrive/issues/511
* https://github.com/skilion/onedrive/issues/510

This issue is a known issue with this repo and is fixed when you use the correct repo. 

The maintained code and repo can be found here: https://github.com/abraunegg/onedrive - with the latest version being `onedrive v2.4.5-24-g2d15e97`

Please follow these instructions to install: https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md

#### Major differences / Enhancements:
- Existing bugs with 'skilion' client fixed
- File upload / download validation to ensure data integrity
- Support for SharePoint / Office 365 Shared Libraries 
- Support for OneDrive Business Shared Folders
- Desktop notifications via libnotify
- Dry-run capability to test configuration changes
- Prevent major OneDrive accidental data deletion after configuration change
- Support National Azure Cloud instances
