### ISSUE TITLE
during syncing lot of conflicted but equal files v.1.1.4

### ISSUE THREAD

**Issue by karolszk** [skilion/onedrive#521]
Hi!

onedrive sync is a great tool, and helps me much during day work.

I successfully built v1.1.4, but notices a lot of unnecessary downloads the same files during synchronization process.

For example:
user@nvme:~/OneDrive/e-book$ md5sum 000000003002006001-nvme.pdf 000000003002006001.pdf 
24b9164a69dda7209c903f52adf10029  000000003002006001-nvme.pdf
24b9164a69dda7209c903f52adf10029  000000003002006001.pdf

Maybe there is a reason:
 ## [1.1.4] - 2020-10-27
### Changed
- Improved synchronization algorithm

I can provide additional details if needed. Thank you.

**Comment by skilion** [comment]
I can't tell what went wrong in the sync process without all the history of the commands you run and the logs.

Does this keep happening? If you can make it happen again then we could debug it.

**Comment by karolszk** [comment]
Hi!
I run the following command:

cd ~/mik/sync-onedrive-linux/onedrive
./onedrive --verbose

and please take a look at the following output log:

Processing 01NBGUGY4P4H4V7WZJHJCL3GMXJGGKDBNC Programista_16_single.pdf
File
The local item has a different hash
The local item is out of sync, renaming...
Downloading e-book/programista/Programista_16_single.pdf... done.
Processing 01NBGUGY7EHE4UTTITE5FZ6AJCNKQ5YYIF Programista_12_2014_Single.pdf
File
The local item has a different hash
The local item is out of sync, renaming...
Downloading e-book/programista/Programista_12_2014_Single.pdf... done.
Processing 01NBGUGYZYVSBMIASRRZCI64IDTBDPHLOV Programista_18_s.pdf
File
The local item has a different hash
The local item is out of sync, renaming...
Downloading e-book/programista/Programista_18_s.pdf... done.
Processing 01NBGUGY5SM6BJDPRL3NAIDSS44PWVCIGZ Programista_17_Single.pdf

and md5 hashes for Programista_16.pdf are:

user@nvme:~/OneDrive/e-book/programista$ md5sum Programista_16_single-nvme.pdf Programista_16_single.pdf 
86e137249b855c11b8278425241de1b6  Programista_16_single-nvme.pdf
86e137249b855c11b8278425241de1b6  Programista_16_single.pdf

**Comment by abraunegg** [comment]
@karolszk 
This bug is due to many factors (file type, account type, file size, OneDrive API), and is fixed in the fork of this client which can be found here: https://github.com/abraunegg/onedrive

#### Major differences / Enhancements:
- Existing bugs with 'skilion' client fixed
- File upload / download validation to ensure data integrity
- Support for SharePoint / Office 365 Shared Libraries 
- Support for OneDrive Business Shared Folders
- Desktop notifications via libnotify
- Dry-run capability to test configuration changes
- Prevent major OneDrive accidental data deletion after configuration change
- Support National Azure Cloud instances
- Supports single tenant applications (required for some enterprise / business environments)
