### ISSUE TITLE
"bad request" due to "dangerous Request.Path" persists despite file deletion

### ISSUE THREAD

**Issue by Elwro** [skilion/onedrive#539]
I'm using 1.1.4 on Ubuntu 21.04. The client was working great until I created a file with a star '*' in its name. Then I started getting these messages:

```
Downloading changes of [REMOVED]
Uploading file ./dzialalnosc_naukowa/sonatabis/wspolna_literatura/elimination_counterexamples/python/*Python*~...HTTP request returned status code 400 (Bad Request)
{
    "error": {
        "code": "invalidRequest",
        "innerError": {
            "client-request-id": "57a65f56-79c3-4251-a5bc-e390aa2681b2",
            "code": "badArgument",
            "date": "2021-09-23T10:14:50",
            "request-id": "57a65f56-79c3-4251-a5bc-e390aa2681b2"
        },
        "message": "A potentially dangerous Request.Path value was detected from the client (*)."
    }
}
```
I have promptly deleted the offending file. However, the issue persists -- the client says it attempts to upload the nonexistent file. (And eventually stops working without uploading any other files.) What should I do?

**Comment by abraunegg** [comment]
@Elwro 

The 'skilion' client does not receive any support ([reference](https://github.com/skilion/onedrive/issues/518#issuecomment-717604726)) and contains issues / defects that put you at risk of data loss. Despite a new version release in Oct 2020, these defects remain. If you wish to use a client which is fully supported please refer to: https://github.com/abraunegg/onedrive

Regarding your specific issue, the 'skilion' codebase does not handle API queries where paths contain wildcards, because the path is not correctly escaped.

**Major differences / Enhancements between codebases:**
- Existing bugs with this client are fixed
- File upload / download validation to ensure data integrity
- Support for SharePoint / Office 365 Shared Libraries
- Support for OneDrive Business Shared Folders
- Support for Docker
- Desktop notifications via libnotify
- Dry-run capability to test configuration changes
- Prevent major OneDrive accidental data deletion after configuration change
- Support National Azure Cloud instances
- Supports single & multi-tenanted applications
- Supports rate limiting of traffic

**Comment by Elwro** [comment]
Thank you very much, I will move to your client
