### ISSUE TITLE
JSONException@std/json.d(508): Key not found: remaining

### ISSUE THREAD

**Issue by Da-NKP** [skilion/onedrive#543]
[Verbose Console Error Log](https://pastebin.com/LEyNDZim)
Version v2.4.13-20-gd99bd5a

Short Summary: remote syncs operated correctly as of 2021-11-16. Attempted dry-runs and verbose (to get extra detail) as well as logging out and logging back in. The OneDrive target points to an active Business Drive folder (again, working fine previously) and config options include setting the following to 'true':
- 'skip_dotfiles'
- 'upload-only'
- 'no_remote_delete'

Not really sure what else to check, but let me know if I can provide any* other helpful information.

* Within reason; I will omit certain details where they are not relevant to exploring the bug or represent data I simply cannot share.

**Comment by abraunegg** [comment]
@Da-NKP 
You are raising this in the wrong location due to your client version. Please follow the correct support process.

The 'skilion' client does not receive any support ([reference](https://github.com/skilion/onedrive/issues/518#issuecomment-717604726)) and contains issues / defects that put you at risk of data loss. Despite a new version release in Oct 2020, these defects remain. If you wish to use a client which is fully supported please refer to: https://github.com/abraunegg/onedrive

**Comment by Da-NKP** [comment]
Whoops! Pretty sure I read this somewhere and just didn't put two and two together. Thanks for the kind heads-up!

**Comment by abraunegg** [comment]
@Da-NKP 
PR for resolution is also available
