### ISSUE TITLE
How to log in onedrive?

### ISSUE THREAD

**Issue by hengxin** [skilion/onedrive#58]
The Doc reads 

```The first time you run the program you will be asked to sign in. The procedure requires a web browser.```

I run this app by `./onedrive` and get the following information:

```
Authorize this app visiting:

https://login.live.com/oauth20_authorize.srf?client_id=000000004C15842F&scope=wl.offline_access%20onedrive.readwrite&response_type=code&redirect_uri=https://login.live.com/oauth20_desktop.srf

Enter the response uri: <CURSOR>
```

What should I enter here (entering id and password for my onedrive account does not work)? How to log in onedrive?

I have tried to change both `client_id` and `client_secret` in `~/.config/onedrive/config`, however, it does not work either.

**Comment by Scimmia22** [comment]
You do exactly what it says. You visit the given URL and log in, then paste the resulting URL

**Comment by hengxin** [comment]
@Scimmia22 Fixed. Thanks.

**Comment by nerak99** [comment]
One drive is great but the msg is not clear and saying, 'do exactly what it says' is not really very friendly (and a bit patronising?).

The message does not make it clear that what is meant is to  
1)  visit the url generated in the cli using your normal web browser and then,  
2) in the microsoft onedrive site,  authorise the linux onedrive program to access your files.

I took the message 'enter the response uri' to mean I had to 'enter' something in the cli, the bit about visiting had scrolled off the screen.

Let us raise a glass to newbies everywhere because we oldbies will not be here forever.

I hope this message will clarify the issue for future users.

**Comment by abraunegg** [comment]
@nerak99 
Thanks for the feedback on the messaging. Will look at making sure this a little clearer in the program and documents.

Additionally, the 'skilion' code appears to have been abandoned by the original author and contains issues that have not been fixed. Any issues, suggestions & feature requests will not be looked at under this github repository.

If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

If you have any issues when using my branch submit your issue against my branch for resolution & management.

**Comment by pmrancuret** [comment]
I've tried following these directions, but it results in a seg fault.  This occurs after visiting the URL, logging in, and entering the resulting URL back into onedrive.

I used the -v option (sudo onedrive -v) , and after entering the response URL, it returns the following (please note that I've replaced the correlation_id with a bunch of X's and the trace_id with a bunch of Y's in this snippet).

onedrive.OneDriveException@src/onedrive.d(403): HTTP request returned status code 400 (Bad Request)
{
    "correlation_id": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
    "error": "invalid_grant",
    "error_codes": [
        70000
    ],
    "error_description": "AADSTS70000: The provided value for the 'code' parameter is not valid. The code has expired.\r\nTrace ID: YYYYYYYY-YYYY-YYYY-YYYY-YYYYYYYYYYYY\r\nCorrelation ID: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX\r\nTimestamp: 2018-09-08 19:41:29Z",
    "timestamp": "2018-09-08 19:41:29Z",
    "trace_id": "YYYYYYYY-YYYY-YYYY-YYYY-YYYYYYYYYYYY"
}
----------------
0x563b921bea9c ???
	???:0
0x563b92234d22 ???
	???:0
0x563b921bd96b ???
	???:0
0x563b921bd7ff ???
	???:0
0x563b921bc136 ???
	???:0
0x563b921bbe7f ???
	???:0
0x563b921b97a7 ???
	???:0
0x563b9230d8be ???
	???:0
0x563b9230da2e ???
	???:0
0x563b9230ddea ???
	???:0
0x563b9230da2e ???
	???:0
0x563b9230dbc0 ???
	???:0
0x563b921b8ea3 ???
	???:0
0x7fbdd37f6b96 __libc_start_main
	???:0
0x563b921b0c99 ???
	???:0
0xffffffffffffffff ???
	???:0
Segmentation fault

I don't know why anything would have expired, everything was done within seconds of logging in using the supplied URL.

Not sure if this is the problem, but my ~/OneDrive folder location is on an ntfs drive partition, which a Windows installation on the same machine actually already has configured as the OneDrive directory.  I tried setting sync_dir="~/test" in the config file (after using mkdir ~/test), hoping it would just make a separate copy for linux.  Perhaps this just isn't going to work for my system?

Thanks for any help you are able to provide!  Let me know if you have other questions or need more details.

**Comment by abraunegg** [comment]
@pmrancuret 
Can you format your post correctly?

Also - the 'skilion' code appears to have been abandoned by the original author and contains issues that have not been fixed. If you wish to use the latest code which contains numerous fixes and enhancements you need clone from here: https://github.com/abraunegg/onedrive

> Not sure if this is the problem, but my /OneDrive folder location is on an ntfs drive partition, which a Windows installation on the same machine actually already has configured as the OneDrive directory. I tried setting sync_dir="/test" in the config file (after using mkdir ~/test), hoping it would just make a separate copy for linux. Perhaps this just isn't going to work for my system?

Setting `sync_dir="/test"` would assume that `/test` is your sync dir, not `~/OneDrive/test/` which you are trying to achieve.

Having the sync dir on a Linux NTFS mount - this may cause issues as well - you 'may' end up with permission errors and the like - this is all untested.

**Comment by pmrancuret** [comment]
@abraunegg Thanks for the quick response!  I really appreciate it, and it's good to see you're keeping a maintained version of this cool project.

> Can you format your post correctly?

I actually spent a bit of time trying to format the original post correctly and gave up.  The bit of code I pasted in contained a bunch of the special markdown characters in it, so it was giving me a hard time.  I'll go back and correct it now that I've had a few minutes to re-learn the markdown language.

> Setting sync_dir="/test" would assume that /test is your sync dir, not ~/OneDrive/test/ which you are trying to achieve.

I actually was trying to use ~/test as the sync dir, not ~/OneDrive/test.  I have my user home directory on the ntfs mount, because the partition with my Ubuntu installation is too small for all of my files, especially for the OneDrive.  A Windows installation also uses that same directory for the user folder (so Windows and Ubuntu share the exact same Documents, Pictures, Music, etc. folders).  So my user home directory already contains OneDrive, but it is the windows incarnation of OneDrive, and isn't interpreted as a directory by linux.  So I was just trying to stay away from ~/OneDrive and use ~/test instead.  When I type `ls -l` from my home directory, I get the following, which shows the OneDrive folder from Windows as a bunch of nonsense.

```
drwxrwx--- 1 root plugdev     0 Sep  8 15:31 '3D Objects'
drwxrwx--- 1 root plugdev     0 Sep  8 15:31  Contacts
drwxrwx--- 1 root plugdev     0 Sep  8 14:19  Desktop
drwxrwx--- 1 root plugdev     0 Sep  8 14:19  Documents
drwxrwx--- 1 root plugdev 32768 Sep  8 15:39  Downloads
drwxrwx--- 1 root plugdev     0 Sep  8 15:31  Favorites
drwxrwx--- 1 root plugdev     0 Sep  7 23:06  Git
drwxrwx--- 1 root plugdev     0 Sep  8 15:31  Links
drwxrwx--- 1 root plugdev     0 Sep  8 14:19  Music
d????????? ? ?    ?           ?            ?  OneDrive
drwxrwx--- 1 root plugdev     0 Sep  8 14:19  Pictures
drwxrwx--- 1 root plugdev     0 Sep  8 14:19  Public
drwxrwx--- 1 root plugdev     0 Sep  8 15:31 'Saved Games'
drwxrwx--- 1 root plugdev  4096 Sep  8 15:31  Searches
drwxrwx--- 1 root plugdev     0 Sep  8 14:19  Templates
drwxrwx--- 1 root plugdev     0 Sep  9 07:55  test
drwxrwx--- 1 root plugdev     0 Sep  8 20:19  Videos
```
I also need to apologize for another glaring omission in my original post.  I forgot to mention that I got onedrive using `apt-get install onedrive`, rather than from cloning the git repo and rebuilding it myself.  Typing `onedrive --version` yields:
`onedrive v1.0.1`

I did have a typo in the config file.  I meant to use `sync_dir="~/test"` but mistyped `sync_dir="/test"` instead (root mount didn't have test folder, home directory did).  It seems to work now that I corrected that.  I was really just using the test folder to try and get something working.  Now I'll set it up with something like `~/LinuxOneDrive` as the sync directory, and use the other config options to only sync what I want, instead of everything.

> Having the sync dir on a Linux NTFS mount - this may cause issues as well - you 'may' end up with permission errors and the like - this is all untested.

Now that I've got it working on an NTFS mount, I suppose you can consider it somewhat tested :)

Thank you again for maintaining this project, and for quickly responding to my post!  Your efforts are greatly appreciated.

**Comment by abraunegg** [comment]
>Typing onedrive --version yields:
>onedrive v1.0.1

Just be aware there are several defects with 'skilion' codebase, a few which appear to have been fixed overnight, but there are still many outstanding.
