### ISSUE TITLE
status code 412 (Precondition Failed) on Moving

### ISSUE THREAD

**Issue by quirinux** [skilion/onedrive#79]
Have got this issues when moved a file, follow the error log:

Moving remote item: ./Pictures/Document5.docx -> ./Pictures/docs/Document5.docx
## onedrive.OneDriveException@src/onedrive.d(337): HTTP request returned status code 412 (Precondition Failed)

??:? std.json.JSONValue onedrive.OneDriveApi.patch!(char).patch(const(char)[], const(char)[]) [0x5941fd]
??:? void sync.SyncEngine.uploadMoveItem(immutable(char)[], immutable(char)[]) [0x59db17]
??:? void main.main(immutable(char)[][]).__dgliteral7(immutable(char)[], immutable(char)[]) [0x58aa3d]
??:? void monitor.Monitor.update(bool) [0x58d895]
??:? _Dmain [0x58a52d]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5a522e]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5a5178]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])_).runAll() [0x5a51ea]
??:? void rt.dmain2._d_run_main(int, char__, extern (C) int function(char[][])_).tryExec(scope void delegate()) [0x5a5178]
??:? _d_run_main [0x5a50e9]
??:? main [0x58c70d]
??:? __libc_start_main [0x595b5f44]
Segment Fault

Think the current line is really 334 and not 337 and might the error occurred because I created a new directory and moved the file into them, so this new path doesn't exist on onedrive yet.

When I tried ti run sync again it downloaded the old file, it should delete it from cloud, and uploaded the new one to cloud again, as shown bellow:

> onedrive -m
> Downloading: ./Pictures/Document5.docx
> Uploading: ./Pictures/docs/Document5.docx

**Comment by abraunegg** [comment]
In main.d there is the following function:

```
void performSync(SyncEngine sync)
{
        int count;
        do {
                try {
                        sync.applyDifferences();
                        sync.scanForDifferences(".");
                        count = -1;
                } catch (SyncException e) {
                        if (++count == 3) throw e;
                        else writeln(e.msg);
                }
        } while (count != -1);
}
```

The call to `sync.applyDifferences();` scans your OneDrive for any changes and download any modifications made there - this always is done first

The call then to `sync.scanForDifferences(".");` scans then the local path for any local changes and then uploads them.

I have been working on a set of patches for a number of items, this included, so that you can configure which direction to sync first

**Comment by abraunegg** [comment]
I will be posting pull request for these changes when I have finished them

**Comment by abraunegg** [comment]
Posted a pull request for a number of items

https://github.com/skilion/onedrive/pull/82

**Comment by thomasfedb** [comment]
@quirinux can you replicate this with the latest commit?

**Comment by dwuttke90** [comment]
having the same issue when uploading files. lets hope this gets fixed soon.

there is a workaround with restarting the service on fail: [https://www.modmy.com/how-sync-onedrive-linux](https://www.modmy.com/how-sync-onedrive-linux)

**Comment by thomasfedb** [comment]
@dwuttke90 can your provide a stack trace for the issue you're having?

**Comment by abraunegg** [comment]
It is all with how OneDrive deals with the return codes.

I have this fixed locally - I plan on submitting a patch for this and a bunch of other things as well

**Comment by dwuttke90** [comment]
@thomasfedb 
thats the stacktrace i get. i had a few of those 412 (Precondition Failed) codes before without crashing the client. just incase that info helps.

`onedrive.OneDriveException@src/onedrive.d(408): HTTP request returned status code 412 (Precondition Failed)
{
    "error": {
        "code": "resourceModified",
        "innerError": {
            "date": "2018-03-14T03:43:22",
            "request-id": "1a43d743-34e6-4a98-8a24-75963bcb9d3b"
        },
        "message": "ETag does not match current item's value"
    }
}
----------------
??:? void onedrive.OneDriveApi.checkHttpCode(ref const(std.json.JSONValue)) [0x921958b8]
??:? std.json.JSONValue onedrive.OneDriveApi.patch!(char).patch(const(char)[], const(char)[]) [0x9219597e]
??:? std.json.JSONValue onedrive.OneDriveApi.updateById(const(char)[], const(char)[], std.json.JSONValue, const(char)[]) [0x921943a7]
??:? void sync.SyncEngine.uploadLastModifiedTime(const(char)[], const(char)[], const(char)[], std.datetime.systime.SysTime) [0x921a088b]
??:? void sync.SyncEngine.uploadNewFile(immutable(char)[]) [0x921a05c4]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x921a0040]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x9219ff63]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x9219ff63]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x9219ff63]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x9219ff63]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x9219ff63]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x9219ff63]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x9219ff63]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x9219ff63]
??:? void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x9219f3a5]
??:? void main.performSync(sync.SyncEngine) [0x9218cc53]
??:? _Dmain [0x9218c8c4]
onedrive -m  19,99s user 2,60s system 5% cpu 7:03,57 total`

@abraunegg 
that would be rly awesome ;)
any chance that "bunch of other things" includes a speed improvement? ;)
since it seems to be a problem with that client. first sync of 3.7GB took me about 2h. uploading is way slower...

**Comment by abraunegg** [comment]
The changes I have cover:

- This issue (412 pre-condition) - plus a whole lot of other 4xx failures that I found
- Logging - log to a file (/var/log/onedrive/onedrive.log)
- http(s) debugging as a flag
- dont sync when just blindly running the application 
- individual folder sync - ie ~/OneDrive/blah/ vs. syncing everything in ~/OneDrive/
- sync from local directory first rather than download first then upload
- upload only (use OneDrive as a one way backup)
- download only

Obviously --local-first option does not accept --download-only option as that would be countering each other.

In terms of performance throughput - upload speeds are would be limited by upload bandwidth from your ISP & potentially a whole lot of other items, however other cloud clients (non OneDrive but still API based) achieve this via threads / multi-threading.

**Comment by dwuttke90** [comment]
cant wait to see those changes.

and ye. multithreading seems a nice idea for speed improvements. if i upload "big" files. i get a pretty stable 500-600KB upload speed.

wrong issue to discuss this...

**Comment by abraunegg** [comment]
Just local github copy to play nice - then will be posting a pull request.

All the changes above are included in my version of the client that I have bundled with MyNAS Storage Appliance - www.mynas.com.au

**Comment by tahder** [comment]
Got the same issue here, when you move folder(s) while on sync will terminate the service.

>  No such file or directory
> Mar 15 16:14:35  systemd[3392]: onedrive.service: Main process exited, code=exited, status=1/FAILURE
> Mar 15 16:14:35  systemd[3392]: onedrive.service: Unit entered failed state.
> Mar 15 16:14:35  systemd[3392]: onedrive.service: Failed with result 'exit-code'.

The remedy is to restart the service.

**Comment by abraunegg** [comment]
@quirinux @tahder 

Can you test with the latest #314 version & report back?

**Comment by abraunegg** [comment]
@quirinux @tahder
Please can you provide an update or close this case

**Comment by abraunegg** [comment]
Considering this issue closed due to no response from original submitter.

If you have further issues please or come back to this, open a new case here: https://github.com/abraunegg/onedrive

**Comment by quirinux** [comment]
that's all good now

**Comment by tahder** [comment]
apology been busy on a couple of days. Still got the issue... as per notice and check online that the folder that I used to move is already existed online and locally not yet updated, maybe when they sync that's the time it will issue occur.

> /home/tahder/dlang/dmd-2.080.1/linux/bin64/../../src/phobos/std/exception.d:515 pure @safe void std.exception.bailOut!(std.json.JSONException).bailOut(immutable(char)[], ulong, const(char[])) [0x57d88b]
> ??:? pure @safe inout(std.json.JSONValue)* std.exception.enforce!(std.json.JSONException).enforce!(inout(std.json.JSONValue)*).enforce(inout(std.json.JSONValue)*, lazy const(char)[], immutable(char)[], ulong) [0x60afe6]
> ??:? inout pure ref @safe inout(std.json.JSONValue) std.json.JSONValue.opIndex(immutable(char)[]) [0x5c22b5]
> src/sync.d:47 itemdb.Item sync.makeItem(ref const(std.json.JSONValue)) [0x5950dd]
> src/sync.d:197 void sync.SyncEngine.applyDifference(std.json.JSONValue, immutable(char)[], bool) [0x595f8e]
> src/sync.d:177 void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[]) [0x595dff]
> src/sync.d:146 void sync.SyncEngine.applyDifferences() [0x595add]
> src/main.d:193 void main.performSync(sync.SyncEngine) [0x584af3]
> src/main.d:121 _Dmain [0x58464f]

i tried dmd-2.079.0 but same issue, I don't know where I can remove the pending transactions.

**Comment by abraunegg** [comment]
@tahder 
What version of the code are you running?

**Comment by tahder** [comment]
@abraunegg I am compiled it  from the source and using Fedora 28.

**Comment by abraunegg** [comment]
@tahder

If you are not using the code from my branc https://github.com/abraunegg/onedrive your not using the lates code or where this issue is resolved

**Comment by tahder** [comment]
@abraunegg yes your branch (the link provided) resolve the issue, as don't know before that this has been forked. Thanks a heap.
Where can I close this? :-)

**Comment by abraunegg** [comment]
This case has already been closed by the original submitter
