### ISSUE TITLE
compile under rasbian / osmc

### ISSUE THREAD

**Issue by CaptainMegane** [skilion/onedrive#88]
Hello there,

just searching couple of month for a nice client for onedrive in linux I found that nice project.
Now my question is, if there is any way to compile it under rasbian/osmc, wich has teh arch armhf. I didnt find the dmd-compiler for that kind of arch.

Any ideas?

Thanks a lot.

BR

Marcus

**Comment by JunpeiAnzai** [comment]
Hi Marcus.

Have you tried ldc-compiler instead of dmd?
ldc package for armhf exists in Debian and build succeeded only modification of Makefile(although my architecture is x86_64 and complier version is 1:1.0.0-1).
Line 1
DC = ldc
Line 19
	$(DC) -O -release -enable-inlining -boundscheck=off $(DFLAGS) $(SOURCES)

**Comment by tronium** [comment]
I have a fork that can be compiled using gdc on arm.  I tried it on armbian (Banana Pro). You can try this and let me know whether it works for you:
https://github.com/tronium/onedrive/commit/703c53b700500d46e73a9f00aae80ed438508e2f

**Comment by CaptainMegane** [comment]
Hey. Thanks for the fork. I will try it and report if its working. Hth Marcus

**Comment by tronium** [comment]
Hi Marcus

The 'uname -p' on Raspberry Pi gives 'unkown' instead of 'arm...'. The Makefile needs to be modified by using 'uname -m' (or 'uname -p -m') to select the gdc as the compiler.

I tested it just now on Raspberry Pi, and found that in patch/std_net_curl.d on line 1851 needed to be changed from:
    @property ref Curl handle() return
to:
    @property ref Curl handle()

It solved the above error, but then there was a new error (and more):

"
gdc -frelease -fno-bounds-check -o onedrive src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/sqlite.d src/sync.d src/upload.d src/util.d patch/etc_c_curl.d patch/std_net_curl.d -lcurl -lsqlite3 -ldl
patch/std_net_curl.d:176: error: module cstring is in file 'std/internal/cstring.d' which cannot be read
import path[0] = /usr/include/d/4.9/arm-linux-gnueabihf
import path[1] = /usr/include/d/4.9
Makefile:35: recipe for target 'onedrive' failed
make: *** [onedrive] Error 1
"

I tried further but there were more new errors. I tested that on my Raspberry Pi with gdc 4.9.2 (no gdc 5 available). My successful setup on Banana Pro used gcc 5.4.0.

**Comment by CaptainMegane** [comment]
Would it be possible to use this package: http://packages.ubuntu.com/search?lang=de&arch=any&keywords=gdc-5-arm-linux-gnueabi

Cant test right now cause im not at home.
Hth and br

Marcus

**Comment by CaptainMegane** [comment]
Hi again.

I now upgraded my raspbian to testing (stretch) branch and installed gdc5. Currently make process is still running with no errors so far. But it takes already 10 minutes to compile. Normal behaviour on single core arm cpu with 700mhz or System freezed? 

Hth and Br

Marcus

**Comment by tronium** [comment]
Mine was about 1 minute.

**Comment by CaptainMegane** [comment]
On raspberry pi 2 700mhz? I overwatch processes while running make via top and it says kswapd0 running 16 to 30 percent cpu time while cc1d is state D with 0.6% but 79% ram usage. Something wrong or just taking long time ans perhaps let run whole night? Oops.. while writing that comment cc1d was killed. So maybe rpi is not powerfull enough to compile or is it a bug in cc1d?

**Comment by CaptainMegane** [comment]
Ah...seems to me that swapfile is to short. Got some errors "cant write to swapfile". So how to fix that problem?

**Comment by CaptainMegane** [comment]
Dmesg prooves: rpi ran out of Memory while compile :-(. Other question: would it work if you send me your compiled binary from banana pro?

**Comment by CaptainMegane** [comment]
Update: Adding a swapfile to raspberry finally did the trick. Compile worked fine. Very nice job.

Hth Marcus

**Comment by tronium** [comment]
Hi
Just about to upload the binary from Banana Pro, but it's no longer needed :) . I checked it before hand on Raspberry Pi 3 and seemed to work fine. I'm glad that you finally able to compile it on yours.

Cheers.

**Comment by Offerel** [comment]
Is it possible to release a binary for Raspbian please?

**Comment by CaptainMegane** [comment]
Hi Offerel,

I could provide you the binary via E-mail.

HTH

Marcus

**Comment by Offerel** [comment]
could you please send the binary to bthordy+github@outlook.com or send me a url via OneDrive or Dropbox?

**Comment by CaptainMegane** [comment]
Hi folks, anybody searching the binary for rasbian:

I made it available on my onedrive:
https://1drv.ms/u/s!AittK8uH_Nx1hOZf8Mai8rNLKrbJeg
Binary was compiled using gdcv5 on raspbian stretch (testing-branch).

HTH

Marcus

**Comment by skilion** [comment]
As of ab592f134e63edae8ee3bed64f7ec9351183e431 you can specify a custom compiler via the DC variable. For example with [LDC](https://wiki.dlang.org/LDC): `make DC=ldmd2`
